### ISSUE TITLE
CI on Windows

### ISSUE THREAD

**Issue by dwijnand** [sbt/io#156]
Forked from @eatkins comment in https://github.com/sbt/io/pull/153#issuecomment-391826258:

> It would be great to add a .appveyor.yml so that we'd run tests against windows as part of CI. I think it would be fine to just test windows on 2.12.x. I'm working on some updates to swoval and have found it useful to have automated windows testing (which otherwise tends to get forgotten).

**Comment by eatkins** [comment]
See https://github.com/sbt/io/pull/160

**Comment by eatkins** [comment]
The .appveyor.yml is now merged in. Someone will still need to turn on appveyor builds for this project within the organization (I think such builds already exist for sbt/sbt, so this should be easy).

**Comment by eed3si9n** [comment]
Added it https://ci.appveyor.com/project/sbt/io/build/1.0.2
