### ISSUE TITLE
IO.zip nullpointerexception if outputfile does not have path info in it

### ISSUE THREAD

**Issue by aappddeevv** [sbt/io#164]
Using `IO.zip(...files.., file("blah.zip"))` fails if blah.zip does not have path information in it.
```sh
()
[error] java.lang.NullPointerException
[error] 	at sbt.io.IO$.createDirectory(IO.scala:221)
[error] 	at sbt.io.IO$.archive(IO.scala:509)
[error] 	at sbt.io.IO$.zip(IO.scala:498)
```
Changing blah.zip to `./blah.zip` works.

**Comment by eed3si9n** [comment]
@aappddeevv Thanks for the report. Would you be interested in fixing this bug?

**Comment by mrveera** [comment]
By adding null check on below line can fix this issue.
https://github.com/sbt/io/blob/896c6f5f38e326f43ecf8d3f2eb8d68ec7a880e3/io/src/main/scala/sbt/io/IO.scala#L607
