### ISSUE TITLE
IOSpecification doesn't work on jdk >= 9

### ISSUE THREAD

**Issue by eatkins** [sbt/io#174]
The uriAsFile method doesn't work for the base java classes because in java 9 because the resources are returned with a "jrt" protocol instead of the "jar" protocol.

**Comment by xuwei-k** [comment]
related (or duplicate?) https://github.com/sbt/io/issues/85

**Comment by eatkins** [comment]
Aah, yes. I resolved part of #85 in https://github.com/sbt/io/pull/175.

**Comment by eed3si9n** [comment]
Closing this as duplicate.
