### ISSUE TITLE
Don't publish repositories information

### ISSUE THREAD

**Issue by gslowikowski** [sbt/io#19]
Versions published to Maven central repository contain repository definition:

``` xml
    <repositories>
        <repository>
            <id>bintraysbtmavenreleases</id>
            <name>bintray-sbt-maven-releases</name>
            <url>https://dl.bintray.com/sbt/maven-releases/</url>
            <layout>default</layout>
        </repository>
    </repositories>
```

This must be something local in releasing person setup, because I cannot reproduce it locally.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/io/commit/e3f9b4c061f668d5d17558c9f65a5917ec14539a
