### ISSUE TITLE
Native Milli code no longer necessary on JDK10 or greater

### ISSUE THREAD

**Issue by cunei** [sbt/io#211]
We can probably modify the Milli code to always use the standard Java calls if the property "java.version" says we are running on JDK10 or greater. The original pull request https://github.com/sbt/io/pull/92, submitted on 2017-12-06, referred to a then-pending [JDK issue](https://bugs.openjdk.java.net/browse/JDK-8177809) whose fix was eventually included in JDK10. We can avoid the JNA dispatching overhead if running on a JDK with a fully working get/setLastModifiedTime() call.

**Comment by eed3si9n** [comment]
Looks like this was fixed in https://github.com/sbt/io/pull/274
