### ISSUE TITLE
Drop 2.10 and (possibly) 2.11 support

### ISSUE THREAD

**Issue by eatkins** [sbt/io#218]
It is becoming onerous to support 2.10 (it doesn't support SAM and there are compiler bugs in 2.10 that have been fixed in later versions, e.g. https://github.com/scala/bug/issues/8450). At this point, I don't really see the value proposition in continuing to publish 2.10 artifacts. I looked at the usages in maven and they are exclusively either part of sbt, zinc or typesafe (there are a few play related artifacts) or only publish a 2.12 target. Given that 0.13.x has been sunset, it seems reasonable to drop the 2.10 support, but perhaps I'm missing something.

**Comment by eed3si9n** [comment]
Until https://github.com/sbt/zinc/pull/607 Zinc's test used to require the target Scala version. Another theoretical purpose of cross building IO was so the plugin author can migrate to new IO while they are still on sbt 0.13, and cross build, or use IO as plain library.
At this point I am open to dropping 2.10 and 2.11.

**Comment by eed3si9n** [comment]
Fixed this in https://github.com/sbt/io/pull/225/commits/2fbfffacfc0e9161b7ea7ff74cb5d2f50f2e0c6f
