### ISSUE TITLE
IOSpecification doesn't work on JDK 13+

### ISSUE THREAD

**Issue by SethTisue** [sbt/io#288]
`testOnly *IOSpecification` fails with

```
[info] ! IO.IO.classLocationPath able to determine containing directories: Exception raised on property evaluation.
[info] > ARG_0: class java.lang.String
[info] > Exception: java.io.IOError: java.lang.RuntimeException: /java.base cannot be represented as URI
```

on JDK 13 and 14 (but not 11; I didn't try 12)

this is on Scala 2.12.10 (I didn't try 2.13.x)

this came up in the Scala community build at e.g. https://scala-ci.typesafe.com/job/scala-2.13.x-jdk14-integrate-community-build/649/artifact/logs/sbt-io-build.log

not sure if related: #85, #174

**Comment by xuwei-k** [comment]
https://github.com/sbt/io/pull/328
