### ISSUE TITLE
Vector or List

### ISSUE THREAD

**Issue by eed3si9n** [sbt/io#5]
Avoid `Seq()` since it can be mutable and all.

**Comment by dwijnand** [comment]
I believe this is resolved with the coding guideline: http://www.scala-sbt.org/0.13/docs/Coding-Guideline.html#Use+specific+datatype+%28%2C+%2C+or+%29+rather+than+.

> Default to `Vector`. Use `List` if constant prepending is needed. Use `Array` if Java interop is needed. Note using mutable collection is perfectly fine within the implementation.
