### ISSUE TITLE
IO.download - support redirects?

### ISSUE THREAD

**Issue by dos65** [sbt/io#61]
Hi. What do you think of adding redirects handling for `download` methods?
For example, github releases use redirects intensively.

**Comment by eed3si9n** [comment]
Library management API comes with Gigahorse that follows redirects by default - https://github.com/sbt/librarymanagement/blob/1.x/core/src/main/scala/sbt/librarymanagement/Http.scala

**Comment by dos65** [comment]
Thanks, it looks like a good alternative to IO
