### ISSUE TITLE
IO 1.0.0-M12 leaked out as sbt 1.0 API

### ISSUE THREAD

**Issue by eed3si9n** [sbt/io#64]
https://github.com/sbt/sbt/blob/v1.0.0-RC2/project/Dependencies.scala

```
  private val ioVersion = "1.0.0-M12"
```

Any changes that are not bincompat with 1.0.0-M12 needs to be pulled out.

**Comment by eed3si9n** [comment]
https://github.com/sbt/io/compare/v1.0.0-M12...v1.0.0-M13 This looks like M-13 is still bincompat.

**Comment by dwijnand** [comment]
Damn.. http://repo1.maven.org/maven2/org/scala-sbt/main_2.12/1.0.0-RC2/main_2.12-1.0.0-RC2.pom

**Comment by dwijnand** [comment]
So, there's nothing to roll back then, right? #50 was part of M12

https://github.com/sbt/io/compare/v1.0.0-M12...1.0.0

**Comment by dwijnand** [comment]
Hehe, I used sbt 1.0.0-RC2's Dependencies.scala as my source of truth, so we've been MiMa-ing against 1.0.0-M12: https://github.com/sbt/io/pull/60/files

**Comment by dwijnand** [comment]
Cross-linking, this was opened in response to sbt/sbt#3378.
