### ISSUE TITLE
Source is internal and has private methods

### ISSUE THREAD

**Issue by larsrh** [sbt/io#67]
The `Source` type, which is used for `watchSources`, is "internal" (why?) and only has private methods. When testing that the files included by `watchSources` are correct, this is very inconvenient.

**Comment by olafurpg** [comment]
While porting sbt-scalatex to sbt 1.0 I hit on this error

```
[error] /Users/ollie/dev/Scalatex/scalatexSbtPlugin/src/main/scala/scalatex/SbtPlugin.scala:52:18: No implicit for Append.Values[Seq[sbt.internal.io.Source], Seq[sbt.io.syntax.File]] found,
[error]   so Seq[sbt.io.syntax.File] cannot be appended to Seq[sbt.internal.io.Source]
[error]     watchSources ++= {
[error]                  ^
[error] one error found
```

I could not find references to watchSources in http://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html Would it be possible to provide an implicit Append for File to Source to ease cross-building?

**Comment by olafurpg** [comment]
FWIW, my workaround is to provide an implicit conversion in a PluginCompat object

```scala
// src/main/scala-sbt-1.0/scalatex/PluginCompat.scala
package scalatex

import sbt._
import sbt.internal.io.Source
object PluginCompat {
  implicit def fileToInternalSource(file: File): Source =
    new Source(file, AllPassFilter, NothingFilter)
}
```

**Comment by dwijnand** [comment]
Let's call this one closed with:

+ https://github.com/sbt/io/pull/74;
+ https://github.com/sbt/sbt/pull/3438; and
+ https://github.com/sbt/sbt/pull/3478

.. no?

**Comment by larsrh** [comment]
:+1:
