### ISSUE TITLE
IO.relativize doesn't work with files with relative paths. (Changed behavior since 0.13)

### ISSUE THREAD

**Issue by smartnetworks** [sbt/io#94]
`IO.relativize` has changed behavior since 0.13. More specifically, it doesn't accept files with relative paths.

The following example fails if inserted into the IOSpec:

```scala
    val currentDir = new File(".").getCanonicalFile
    val currentFile = new File("build.sbt")
    IO.relativize(currentDir, currentFile) shouldBe Some("build.sbt")  // Fails! None is returned.
```

If `currentFile` is replaced with `new File("build.sbt").getAbsoluteFile`, the method works as expected.

This problem has been introduced in SBT 1.0. Tested version of SBT is 1.0.4.

**Comment by eed3si9n** [comment]
I think this was a behavior introduced by #33 (and followed up by #34 and #56) to fix #32 caused by #18.

Here's 0.13

```scala
  /**
   * Returns the path for `file` relative to directory `base` or None if `base` is not a parent of `file`.
   * If `file` or `base` are not absolute, they are first resolved against the current working directory.
   */
  def relativize(base: File, file: File): Option[String] =
    {
      val pathString = file.getAbsolutePath
      baseFileString(base) flatMap
        {
          baseString =>
            {
              if (pathString.startsWith(baseString))
                Some(pathString.substring(baseString.length))
              else
                None
            }
        }
    }
```

Given that we see `val pathString = file.getAbsolutePath`, I agree this is a regression.

**Comment by dwijnand** [comment]
Is it not a change in behaviour that was accepted with https://github.com/sbt/io/pull/18?

**Comment by eed3si9n** [comment]
I don't think the intention of the #18 was to discontinue the support of `file` parameter being relative.

**Comment by dwijnand** [comment]
I'm happy to have a look and see if we can reverse the regression.
